### RANDOM FOREST CLASSIFICATION

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df=pd.read_csv('Travel.csv')

In [3]:
df.head()

CustomerID  ProdTaken   Age    TypeofContact  CityTier  DurationOfPitch  \
0      200000          1  41.0     Self Enquiry         3              6.0   
1      200001          0  49.0  Company Invited         1             14.0   
2      200002          1  37.0     Self Enquiry         1              8.0   
3      200003          0  33.0  Company Invited         1              9.0   
4      200004          0   NaN     Self Enquiry         1              8.0   

       Occupation  Gender  NumberOfPersonVisiting  NumberOfFollowups  \
0        Salaried  Female                       3                3.0   
1        Salaried    Male                       3                4.0   
2     Free Lancer    Male                       3                4.0   
3        Salaried  Female                       2                3.0   
4  Small Business    Male                       2                3.0   

  ProductPitched  PreferredPropertyStar MaritalStatus  NumberOfTrips  \
0         Deluxe                    3.0        Single            1.0   
1         Deluxe                    4.0      Divorced            2.0   
2          Basic                    3.0        Single            7.0   
3          Basic                    3.0      Divorced            2.0   
4          Basic                    4.0      Divorced            1.0   

   Passport  PitchSatisfactionScore  OwnCar  NumberOfChildrenVisiting  \
0         1                       2       1                       0.0   
1         0                       3       1                       2.0   
2         1                       3       0                       0.0   
3         1                       5       1                       1.0   
4         0                       5       1                       0.0   

  Designation  MonthlyIncome  
0     Manager        20993.0  
1     Manager        20130.0  
2   Executive        17090.0  
3   Executive        17909.0  
4   Executive        18468.0

In [4]:
col=df.columns

In [5]:
col

Index(['CustomerID', 'ProdTaken', 'Age', 'TypeofContact', 'CityTier',
       'DurationOfPitch', 'Occupation', 'Gender', 'NumberOfPersonVisiting',
       'NumberOfFollowups', 'ProductPitched', 'PreferredPropertyStar',
       'MaritalStatus', 'NumberOfTrips', 'Passport', 'PitchSatisfactionScore',
       'OwnCar', 'NumberOfChildrenVisiting', 'Designation', 'MonthlyIncome'],
      dtype='object')

In [6]:
for feature in col:
    print(feature)
    print(df[feature].unique())

CustomerID
[200000 200001 200002 ... 204885 204886 204887]
ProdTaken
[1 0]
Age
[41. 49. 37. 33. nan 32. 59. 30. 38. 36. 35. 31. 34. 28. 29. 22. 53. 21.
 42. 44. 46. 39. 24. 43. 50. 27. 26. 48. 55. 45. 56. 23. 51. 40. 54. 58.
 20. 25. 19. 57. 52. 47. 18. 60. 61.]
TypeofContact
['Self Enquiry' 'Company Invited' nan]
CityTier
[3 1 2]
DurationOfPitch
[  6.  14.   8.   9.  30.  29.  33.  22.  21.  32.  25.  27.  11.  17.
  15.  13.  12.  16.  10.  31.  18.  nan  24.  35.  28.  20.  26.  34.
  23.   5.  19. 126.   7.  36. 127.]
Occupation
['Salaried' 'Free Lancer' 'Small Business' 'Large Business']
Gender
['Female' 'Male' 'Fe Male']
NumberOfPersonVisiting
[3 2 1 4 5]
NumberOfFollowups
[ 3.  4.  2.  5. nan  1.  6.]
ProductPitched
['Deluxe' 'Basic' 'Standard' 'Super Deluxe' 'King']
PreferredPropertyStar
[ 3.  4.  5. nan]
MaritalStatus
['Single' 'Divorced' 'Married' 'Unmarried']
NumberOfTrips
[ 1.  2.  7.  5.  6.  3.  4. 19. 21.  8. nan 20. 22.]
Passport
[1 0]
PitchSatisfactionScore
[2 3 5 4 1]

In [7]:
df['Gender'].unique()

array(['Female', 'Male', 'Fe Male'], dtype=object)

In [8]:
### female is in the form fe male 
df['Gender']=df['Gender'].replace('Fe Male','Female')

In [9]:
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [10]:
df['Gender'].value_counts(
)

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [11]:
df['MaritalStatus'].unique()

array(['Single', 'Divorced', 'Married', 'Unmarried'], dtype=object)

In [12]:
df['MaritalStatus']=df['MaritalStatus'].replace('Unmarried','Single')

In [13]:
df['MaritalStatus'].unique()

array(['Single', 'Divorced', 'Married'], dtype=object)

In [14]:
for feature in col:
    print(feature)
    print(df[feature].unique())

CustomerID
[200000 200001 200002 ... 204885 204886 204887]
ProdTaken
[1 0]
Age
[41. 49. 37. 33. nan 32. 59. 30. 38. 36. 35. 31. 34. 28. 29. 22. 53. 21.
 42. 44. 46. 39. 24. 43. 50. 27. 26. 48. 55. 45. 56. 23. 51. 40. 54. 58.
 20. 25. 19. 57. 52. 47. 18. 60. 61.]
TypeofContact
['Self Enquiry' 'Company Invited' nan]
CityTier
[3 1 2]
DurationOfPitch
[  6.  14.   8.   9.  30.  29.  33.  22.  21.  32.  25.  27.  11.  17.
  15.  13.  12.  16.  10.  31.  18.  nan  24.  35.  28.  20.  26.  34.
  23.   5.  19. 126.   7.  36. 127.]
Occupation
['Salaried' 'Free Lancer' 'Small Business' 'Large Business']
Gender
['Female' 'Male']
NumberOfPersonVisiting
[3 2 1 4 5]
NumberOfFollowups
[ 3.  4.  2.  5. nan  1.  6.]
ProductPitched
['Deluxe' 'Basic' 'Standard' 'Super Deluxe' 'King']
PreferredPropertyStar
[ 3.  4.  5. nan]
MaritalStatus
['Single' 'Divorced' 'Married']
NumberOfTrips
[ 1.  2.  7.  5.  6.  3.  4. 19. 21.  8. nan 20. 22.]
Passport
[1 0]
PitchSatisfactionScore
[2 3 5 4 1]
OwnCar
[1 0]
NumberOf

In [15]:
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [16]:
df.head(2)

CustomerID  ProdTaken   Age    TypeofContact  CityTier  DurationOfPitch  \
0      200000          1  41.0     Self Enquiry         3              6.0   
1      200001          0  49.0  Company Invited         1             14.0   

  Occupation  Gender  NumberOfPersonVisiting  NumberOfFollowups  \
0   Salaried  Female                       3                3.0   
1   Salaried    Male                       3                4.0   

  ProductPitched  PreferredPropertyStar MaritalStatus  NumberOfTrips  \
0         Deluxe                    3.0        Single            1.0   
1         Deluxe                    4.0      Divorced            2.0   

   Passport  PitchSatisfactionScore  OwnCar  NumberOfChildrenVisiting  \
0         1                       2       1                       0.0   
1         0                       3       1                       2.0   

  Designation  MonthlyIncome  
0     Manager        20993.0  
1     Manager        20130.0

In [17]:
df['Age']=df['Age'].fillna(df['Age'].mean())

In [18]:
df['Age'].isnull().sum()

np.int64(0)

In [19]:
x=df['TypeofContact'].mode()[0]
x

'Self Enquiry'

In [20]:
df['TypeofContact']=df['TypeofContact'].fillna(x)

In [21]:
df['TypeofContact'].isnull().sum()

np.int64(0)

In [22]:
for feature in col:
    print(feature)
    print(df[feature].unique())

CustomerID
[200000 200001 200002 ... 204885 204886 204887]
ProdTaken
[1 0]
Age
[41.         49.         37.         33.         37.62226512 32.
 59.         30.         38.         36.         35.         31.
 34.         28.         29.         22.         53.         21.
 42.         44.         46.         39.         24.         43.
 50.         27.         26.         48.         55.         45.
 56.         23.         51.         40.         54.         58.
 20.         25.         19.         57.         52.         47.
 18.         60.         61.        ]
TypeofContact
['Self Enquiry' 'Company Invited']
CityTier
[3 1 2]
DurationOfPitch
[  6.  14.   8.   9.  30.  29.  33.  22.  21.  32.  25.  27.  11.  17.
  15.  13.  12.  16.  10.  31.  18.  nan  24.  35.  28.  20.  26.  34.
  23.   5.  19. 126.   7.  36. 127.]
Occupation
['Salaried' 'Free Lancer' 'Small Business' 'Large Business']
Gender
['Female' 'Male']
NumberOfPersonVisiting
[3 2 1 4 5]
NumberOfFollowups
[ 3.  4.  2.  5. 

In [23]:
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                           0
TypeofContact                 0
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [24]:
df['DurationOfPitch'].unique()

array([  6.,  14.,   8.,   9.,  30.,  29.,  33.,  22.,  21.,  32.,  25.,
        27.,  11.,  17.,  15.,  13.,  12.,  16.,  10.,  31.,  18.,  nan,
        24.,  35.,  28.,  20.,  26.,  34.,  23.,   5.,  19., 126.,   7.,
        36., 127.])

In [25]:
df['DurationOfPitch'].isnull().sum()

np.int64(251)

In [26]:
df['DurationOfPitch']=df['DurationOfPitch'].fillna(df['DurationOfPitch'].mean())

In [27]:
df['DurationOfPitch'].isnull().sum()

np.int64(0)

In [28]:
df['NumberOfFollowups'].isnull().sum()

np.int64(45)

In [29]:

df['NumberOfFollowups'].unique()

array([ 3.,  4.,  2.,  5., nan,  1.,  6.])

In [30]:
df['NumberOfFollowups'].value_counts()


NumberOfFollowups
4.0    2068
3.0    1466
5.0     768
2.0     229
1.0     176
6.0     136
Name: count, dtype: int64

In [31]:
df['NumberOfFollowups']=df['NumberOfFollowups'].fillna(df['NumberOfFollowups'].mean())

In [32]:
df['NumberOfFollowups'].isnull().sum()


np.int64(0)

In [33]:
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                           0
TypeofContact                 0
CityTier                      0
DurationOfPitch               0
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups             0
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [34]:
df['PreferredPropertyStar'].unique(
    
)

array([ 3.,  4.,  5., nan])

In [35]:
df['PreferredPropertyStar']=df['PreferredPropertyStar'].fillna(df['PreferredPropertyStar'].mode()[0])

In [36]:
df['PreferredPropertyStar'].isnull().sum()

np.int64(0)

In [37]:
df['NumberOfTrips']=df['NumberOfTrips'].fillna(df['NumberOfTrips'].mode()[0])

In [38]:
df.isnull().sum(
    
)

CustomerID                    0
ProdTaken                     0
Age                           0
TypeofContact                 0
CityTier                      0
DurationOfPitch               0
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups             0
ProductPitched                0
PreferredPropertyStar         0
MaritalStatus                 0
NumberOfTrips                 0
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [39]:
df['NumberOfChildrenVisiting']=df['NumberOfChildrenVisiting'].fillna(df['NumberOfChildrenVisiting'].mode()[0])

In [40]:
df['MonthlyIncome']=df['MonthlyIncome'].fillna(df['MonthlyIncome'].mean())

In [41]:
df.isnull().sum(
    
)

CustomerID                  0
ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

In [42]:
df.drop_duplicates(keep='first',inplace=True)

In [43]:
df[df.duplicated()]

Empty DataFrame
Columns: [CustomerID, ProdTaken, Age, TypeofContact, CityTier, DurationOfPitch, Occupation, Gender, NumberOfPersonVisiting, NumberOfFollowups, ProductPitched, PreferredPropertyStar, MaritalStatus, NumberOfTrips, Passport, PitchSatisfactionScore, OwnCar, NumberOfChildrenVisiting, Designation, MonthlyIncome]
Index: []

In [44]:
df.shape

(4888, 20)

In [45]:
df.head()

CustomerID  ProdTaken        Age    TypeofContact  CityTier  \
0      200000          1  41.000000     Self Enquiry         3   
1      200001          0  49.000000  Company Invited         1   
2      200002          1  37.000000     Self Enquiry         1   
3      200003          0  33.000000  Company Invited         1   
4      200004          0  37.622265     Self Enquiry         1   

   DurationOfPitch      Occupation  Gender  NumberOfPersonVisiting  \
0              6.0        Salaried  Female                       3   
1             14.0        Salaried    Male                       3   
2              8.0     Free Lancer    Male                       3   
3              9.0        Salaried  Female                       2   
4              8.0  Small Business    Male                       2   

   NumberOfFollowups ProductPitched  PreferredPropertyStar MaritalStatus  \
0                3.0         Deluxe                    3.0        Single   
1                4.0         Deluxe                    4.0      Divorced   
2                4.0          Basic                    3.0        Single   
3                3.0          Basic                    3.0      Divorced   
4                3.0          Basic                    4.0      Divorced   

   NumberOfTrips  Passport  PitchSatisfactionScore  OwnCar  \
0            1.0         1                       2       1   
1            2.0         0                       3       1   
2            7.0         1                       3       0   
3            2.0         1                       5       1   
4            1.0         0                       5       1   

   NumberOfChildrenVisiting Designation  MonthlyIncome  
0                       0.0     Manager        20993.0  
1                       2.0     Manager        20130.0  
2                       0.0   Executive        17090.0  
3                       1.0   Executive        17909.0  
4                       0.0   Executive        18468.0

In [46]:
### number person visting and number chlidern visting add to cloumn total visting people
df['Total_visting_people']=df['NumberOfChildrenVisiting']+df['NumberOfPersonVisiting']

In [47]:
df.head()

CustomerID  ProdTaken        Age    TypeofContact  CityTier  \
0      200000          1  41.000000     Self Enquiry         3   
1      200001          0  49.000000  Company Invited         1   
2      200002          1  37.000000     Self Enquiry         1   
3      200003          0  33.000000  Company Invited         1   
4      200004          0  37.622265     Self Enquiry         1   

   DurationOfPitch      Occupation  Gender  NumberOfPersonVisiting  \
0              6.0        Salaried  Female                       3   
1             14.0        Salaried    Male                       3   
2              8.0     Free Lancer    Male                       3   
3              9.0        Salaried  Female                       2   
4              8.0  Small Business    Male                       2   

   NumberOfFollowups  ... PreferredPropertyStar  MaritalStatus NumberOfTrips  \
0                3.0  ...                   3.0         Single           1.0   
1                4.0  ...                   4.0       Divorced           2.0   
2                4.0  ...                   3.0         Single           7.0   
3                3.0  ...                   3.0       Divorced           2.0   
4                3.0  ...                   4.0       Divorced           1.0   

   Passport  PitchSatisfactionScore  OwnCar  NumberOfChildrenVisiting  \
0         1                       2       1                       0.0   
1         0                       3       1                       2.0   
2         1                       3       0                       0.0   
3         1                       5       1                       1.0   
4         0                       5       1                       0.0   

   Designation MonthlyIncome  Total_visting_people  
0      Manager       20993.0                   3.0  
1      Manager       20130.0                   5.0  
2    Executive       17090.0                   3.0  
3    Executive       17909.0                   3.0  
4    Executive       18468.0                   2.0  

[5 rows x 21 columns]

In [48]:
df.drop(['NumberOfChildrenVisiting','NumberOfPersonVisiting'],inplace=True,axis=1)

In [49]:
df.head()

CustomerID  ProdTaken        Age    TypeofContact  CityTier  \
0      200000          1  41.000000     Self Enquiry         3   
1      200001          0  49.000000  Company Invited         1   
2      200002          1  37.000000     Self Enquiry         1   
3      200003          0  33.000000  Company Invited         1   
4      200004          0  37.622265     Self Enquiry         1   

   DurationOfPitch      Occupation  Gender  NumberOfFollowups ProductPitched  \
0              6.0        Salaried  Female                3.0         Deluxe   
1             14.0        Salaried    Male                4.0         Deluxe   
2              8.0     Free Lancer    Male                4.0          Basic   
3              9.0        Salaried  Female                3.0          Basic   
4              8.0  Small Business    Male                3.0          Basic   

   PreferredPropertyStar MaritalStatus  NumberOfTrips  Passport  \
0                    3.0        Single            1.0         1   
1                    4.0      Divorced            2.0         0   
2                    3.0        Single            7.0         1   
3                    3.0      Divorced            2.0         1   
4                    4.0      Divorced            1.0         0   

   PitchSatisfactionScore  OwnCar Designation  MonthlyIncome  \
0                       2       1     Manager        20993.0   
1                       3       1     Manager        20130.0   
2                       3       0   Executive        17090.0   
3                       5       1   Executive        17909.0   
4                       5       1   Executive        18468.0   

   Total_visting_people  
0                   3.0  
1                   5.0  
2                   3.0  
3                   3.0  
4                   2.0

In [50]:
df.shape

(4888, 19)

In [51]:
num_feature=[feature for feature in df.columns if df[feature].dtype !='O']

In [52]:
print('length of numeric features is',len(num_feature))

length of numeric features is 13


In [53]:
df.drop('CustomerID',inplace=True,axis=1)

In [54]:
df.head()

ProdTaken        Age    TypeofContact  CityTier  DurationOfPitch  \
0          1  41.000000     Self Enquiry         3              6.0   
1          0  49.000000  Company Invited         1             14.0   
2          1  37.000000     Self Enquiry         1              8.0   
3          0  33.000000  Company Invited         1              9.0   
4          0  37.622265     Self Enquiry         1              8.0   

       Occupation  Gender  NumberOfFollowups ProductPitched  \
0        Salaried  Female                3.0         Deluxe   
1        Salaried    Male                4.0         Deluxe   
2     Free Lancer    Male                4.0          Basic   
3        Salaried  Female                3.0          Basic   
4  Small Business    Male                3.0          Basic   

   PreferredPropertyStar MaritalStatus  NumberOfTrips  Passport  \
0                    3.0        Single            1.0         1   
1                    4.0      Divorced            2.0         0   
2                    3.0        Single            7.0         1   
3                    3.0      Divorced            2.0         1   
4                    4.0      Divorced            1.0         0   

   PitchSatisfactionScore  OwnCar Designation  MonthlyIncome  \
0                       2       1     Manager        20993.0   
1                       3       1     Manager        20130.0   
2                       3       0   Executive        17090.0   
3                       5       1   Executive        17909.0   
4                       5       1   Executive        18468.0   

   Total_visting_people  
0                   3.0  
1                   5.0  
2                   3.0  
3                   3.0  
4                   2.0

In [55]:
num_feature=[feature for feature in df.columns if df[feature].dtype !='O']

In [56]:
print('length of numeric features is',len(num_feature))
print(num_feature)

length of numeric features is 12
['ProdTaken', 'Age', 'CityTier', 'DurationOfPitch', 'NumberOfFollowups', 'PreferredPropertyStar', 'NumberOfTrips', 'Passport', 'PitchSatisfactionScore', 'OwnCar', 'MonthlyIncome', 'Total_visting_people']


In [57]:
cat_feature=[feature for feature in df.columns if df[feature].dtype=='O']
print('length of cat_feature features is',len(cat_feature))
print(cat_feature)


length of cat_feature features is 6
['TypeofContact', 'Occupation', 'Gender', 'ProductPitched', 'MaritalStatus', 'Designation']


In [58]:
x=df.drop(['ProdTaken'],axis=1)

In [59]:
x

Age    TypeofContact  CityTier  DurationOfPitch      Occupation  \
0     41.000000     Self Enquiry         3              6.0        Salaried   
1     49.000000  Company Invited         1             14.0        Salaried   
2     37.000000     Self Enquiry         1              8.0     Free Lancer   
3     33.000000  Company Invited         1              9.0        Salaried   
4     37.622265     Self Enquiry         1              8.0  Small Business   
...         ...              ...       ...              ...             ...   
4883  49.000000     Self Enquiry         3              9.0  Small Business   
4884  28.000000  Company Invited         1             31.0        Salaried   
4885  52.000000     Self Enquiry         3             17.0        Salaried   
4886  19.000000     Self Enquiry         3             16.0  Small Business   
4887  36.000000     Self Enquiry         1             14.0        Salaried   

      Gender  NumberOfFollowups ProductPitched  PreferredPropertyStar  \
0     Female                3.0         Deluxe                    3.0   
1       Male                4.0         Deluxe                    4.0   
2       Male                4.0          Basic                    3.0   
3     Female                3.0          Basic                    3.0   
4       Male                3.0          Basic                    4.0   
...      ...                ...            ...                    ...   
4883    Male                5.0         Deluxe                    4.0   
4884    Male                5.0          Basic                    3.0   
4885  Female                4.0       Standard                    4.0   
4886    Male                4.0          Basic                    3.0   
4887    Male                4.0          Basic                    4.0   

     MaritalStatus  NumberOfTrips  Passport  PitchSatisfactionScore  OwnCar  \
0           Single            1.0         1                       2       1   
1         Divorced            2.0         0                       3       1   
2           Single            7.0         1                       3       0   
3         Divorced            2.0         1                       5       1   
4         Divorced            1.0         0                       5       1   
...            ...            ...       ...                     ...     ...   
4883        Single            2.0         1                       1       1   
4884        Single            3.0         1                       3       1   
4885       Married            7.0         0                       1       1   
4886        Single            3.0         0                       5       0   
4887        Single            3.0         1                       3       1   

         Designation  MonthlyIncome  Total_visting_people  
0            Manager        20993.0                   3.0  
1            Manager        20130.0                   5.0  
2          Executive        17090.0                   3.0  
3          Executive        17909.0                   3.0  
4          Executive        18468.0                   2.0  
...              ...            ...                   ...  
4883         Manager        26576.0                   4.0  
4884       Executive        21212.0                   6.0  
4885  Senior Manager        31820.0                   7.0  
4886       Executive        20289.0                   5.0  
4887       Executive        24041.0                   6.0  

[4888 rows x 17 columns]

In [60]:
y=df['ProdTaken']

In [61]:
y

0       1
1       0
2       1
3       0
4       0
       ..
4883    1
4884    1
4885    1
4886    1
4887    1
Name: ProdTaken, Length: 4888, dtype: int64

In [62]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=45)

In [63]:
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer
one=OneHotEncoder(drop='first')
scale=StandardScaler()

In [64]:
cat_feature=x.select_dtypes(include='object').columns
num_feature=x.select_dtypes(exclude='object').columns
print(cat_feature,len(cat_feature))
print(num_feature,len(num_feature))

Index(['TypeofContact', 'Occupation', 'Gender', 'ProductPitched',
       'MaritalStatus', 'Designation'],
      dtype='object') 6
Index(['Age', 'CityTier', 'DurationOfPitch', 'NumberOfFollowups',
       'PreferredPropertyStar', 'NumberOfTrips', 'Passport',
       'PitchSatisfactionScore', 'OwnCar', 'MonthlyIncome',
       'Total_visting_people'],
      dtype='object') 11


In [65]:
process=ColumnTransformer([('onehotencoder',one,cat_feature),
                           ('standardscale',scale,num_feature)],remainder='passthrough')

In [66]:
process

ColumnTransformer(remainder='passthrough',
                  transformers=[('onehotencoder', OneHotEncoder(drop='first'),
                                 Index(['TypeofContact', 'Occupation', 'Gender', 'ProductPitched',
       'MaritalStatus', 'Designation'],
      dtype='object')),
                                ('standardscale', StandardScaler(),
                                 Index(['Age', 'CityTier', 'DurationOfPitch', 'NumberOfFollowups',
       'PreferredPropertyStar', 'NumberOfTrips', 'Passport',
       'PitchSatisfactionScore', 'OwnCar', 'MonthlyIncome',
       'Total_visting_people'],
      dtype='object'))])

In [67]:
x_train=process.fit_transform(x_train)

In [68]:
x_test=process.transform(x_test)

In [69]:
x_train

array([[ 1.        ,  0.        ,  0.        , ..., -1.26754356,
        -0.43692616, -0.06881353],
       [ 1.        ,  0.        ,  1.        , ...,  0.78892752,
        -0.44211331,  0.63924147],
       [ 1.        ,  1.        ,  0.        , ...,  0.78892752,
        -1.02326649, -0.77686853],
       ...,
       [ 1.        ,  0.        ,  1.        , ...,  0.78892752,
         0.14864571, -0.77686853],
       [ 1.        ,  0.        ,  0.        , ...,  0.78892752,
         1.0556289 ,  0.63924147],
       [ 1.        ,  0.        ,  0.        , ...,  0.78892752,
         0.16939432, -0.06881353]], shape=(3910, 26))

In [70]:
pd.DataFrame(x_train)


0    1    2    3    4    5    6    7    8    9   ...        16  \
0     1.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  ... -0.722070   
1     1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ... -0.722070   
2     1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ... -0.722070   
3     1.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  ... -0.722070   
4     0.0  0.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  ... -0.722070   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...   
3905  1.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  ... -0.722070   
3906  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.450529   
3907  1.0  0.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  ... -0.722070   
3908  1.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  0.0  1.0  ...  0.364230   
3909  1.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  ...  1.450529   

            17        18        19        20       21        22        23  \
0     1.490319  0.291757 -0.725693 -0.108965 -0.63557 -0.775296 -1.267544   
1    -1.014553  0.291757 -0.725693 -0.108965  1.57339 -0.045715  0.788928   
2    -0.298875 -0.704516 -0.725693  0.442918  1.57339  0.683865  0.788928   
3     1.013201  0.291757 -0.725693 -0.660848  1.57339 -0.045715 -1.267544   
4     2.325276  1.288030 -0.725693  0.994801 -0.63557 -0.045715 -1.267544   
...        ...       ...       ...       ...      ...       ...       ...   
3905 -0.775994  0.291757 -0.725693  2.650449  1.57339  0.683865 -1.267544   
3906 -0.179596 -0.704516 -0.725693 -0.660848 -0.63557 -0.045715 -1.267544   
3907  1.728878 -1.700788 -0.725693  0.442918  1.57339  0.683865  0.788928   
3908 -1.014553  1.288030  1.794254 -0.660848 -0.63557  0.683865  0.788928   
3909  0.178243  1.288030 -0.725693 -0.660848 -0.63557  0.683865  0.788928   

            24        25  
0    -0.436926 -0.068814  
1    -0.442113  0.639241  
2    -1.023266 -0.776869  
3    -1.205777 -1.484924  
4     2.854802  0.639241  
...        ...       ...  
3905 -0.370838  2.055351  
3906 -1.170620 -0.776869  
3907  0.148646 -0.776869  
3908  1.055629  0.639241  
3909  0.169394 -0.068814  

[3910 rows x 26 columns]

In [71]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier



In [72]:
models={
    'logistic':LogisticRegression(),
    'random':RandomForestClassifier(),
    'desicion':DecisionTreeClassifier(),
    'knearest':KNeighborsClassifier(),
    'gussian':GaussianNB()
}

In [73]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,precision_score,f1_score,recall_score


In [74]:
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(x_train,y_train)
    
    
    y_train_pred=model.predict(x_train)
    y_test_pred=model.predict(x_test)
    
    print(list(models.keys())[i])
    
    print("prediction for x_train")
    print("classification_report",classification_report(y_train,y_train_pred))
    print('confusion_matrix',confusion_matrix(y_train,y_train_pred))
    print("accuray_score",accuracy_score(y_train,y_train_pred))
    print("precission_score",precision_score(y_train,y_train_pred))
    print("f1_score",f1_score(y_train,y_train_pred))
    print("recall_score",recall_score(y_train,y_train_pred))
    
    print('--'*35)
    
    print('prediction for x_test')
    print("classification_report",classification_report(y_test,y_test_pred))
    print('confusion_matrix',confusion_matrix(y_test,y_test_pred))
    print("accuray_score",accuracy_score(y_test,y_test_pred))
    print("precission_score",precision_score(y_test,y_test_pred))
    print("f1_score",f1_score(y_test,y_test_pred))
    print("recall_score",recall_score(y_test,y_test_pred))
    
    print('=='*35)
    
    
    

logistic
prediction for x_train
classification_report               precision    recall  f1-score   support

           0       0.86      0.97      0.91      3193
           1       0.69      0.30      0.42       717

    accuracy                           0.85      3910
   macro avg       0.78      0.63      0.66      3910
weighted avg       0.83      0.85      0.82      3910

confusion_matrix [[3099   94]
 [ 504  213]]
accuray_score 0.8470588235294118
precission_score 0.6938110749185668
f1_score 0.416015625
recall_score 0.29707112970711297
----------------------------------------------------------------------
prediction for x_test
classification_report               precision    recall  f1-score   support

           0       0.85      0.98      0.91       775
           1       0.79      0.33      0.46       203

    accuracy                           0.84       978
   macro avg       0.82      0.65      0.68       978
weighted avg       0.83      0.84      0.81       978

confusion_

In [79]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint
param_dist = {
    'n_estimators':randint(50, 500),  # Number of trees
    'max_depth': [None, 10, 20, 30, 50],  # Max depth of each tree
    'min_samples_split': randint(2, 20),  # Minimum samples to split a node
    'min_samples_leaf': randint(1, 10),  # Minimum samples at each leaf node
    'max_features': ['sqrt', 'log2'],  # Number of features to consider at each split
    'bootstrap': [True, False]  # Bootstrap samples when building trees
}

In [80]:
param_dist

{'n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen at 0x2042c98eff0>,
 'max_depth': [None, 10, 20, 30, 50],
 'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen at 0x2042ca455e0>,
 'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen at 0x204429dcb00>,
 'max_features': ['sqrt', 'log2'],
 'bootstrap': [True, False]}

In [81]:
rf=RandomForestClassifier()
rc=RandomizedSearchCV(estimator=rf,param_distributions=param_dist,cv=5,n_iter=100,verbose=3,n_jobs=-1)

In [82]:
rc.fit(x_train,y_train)

Fitting 5 folds for each of 100 candidates, totalling 500 fits


RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'bootstrap': [True, False],
                                        'max_depth': [None, 10, 20, 30, 50],
                                        'max_features': ['sqrt', 'log2'],
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x00000204429DCB00>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000002042CA455E0>,
                                        'n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000002042C98EFF0>},
                   verbose=3)

In [84]:
rc.best_params_

{'bootstrap': False,
 'max_depth': 50,
 'max_features': 'sqrt',
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 295}

In [85]:
rf=RandomForestClassifier(n_estimators=294,bootstrap=False,max_depth=20,max_features="sqrt",min_samples_leaf=2,min_samples_split=7)

In [86]:
rf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=False, max_depth=20, min_samples_leaf=2,
                       min_samples_split=7, n_estimators=294)

In [88]:
y_train_pred=rf.predict(x_train)
y_test_pred=rf.predict(x_test)
    

    
print("prediction for x_train")
print("classification_report",classification_report(y_train,y_train_pred))
print('confusion_matrix',confusion_matrix(y_train,y_train_pred))
print("accuray_score",accuracy_score(y_train,y_train_pred))
print("precission_score",precision_score(y_train,y_train_pred))
print("f1_score",f1_score(y_train,y_train_pred))
print("recall_score",recall_score(y_train,y_train_pred))
    
print('--'*35)
    
print('prediction for x_test')
print("classification_report",classification_report(y_test,y_test_pred))
print('confusion_matrix',confusion_matrix(y_test,y_test_pred))
print("accuray_score",accuracy_score(y_test,y_test_pred))
print("precission_score",precision_score(y_test,y_test_pred))
print("f1_score",f1_score(y_test,y_test_pred))
print("recall_score",recall_score(y_test,y_test_pred))
    
print('=='*35)

prediction for x_train
classification_report               precision    recall  f1-score   support

           0       1.00      1.00      1.00      3193
           1       1.00      0.98      0.99       717

    accuracy                           1.00      3910
   macro avg       1.00      0.99      0.99      3910
weighted avg       1.00      1.00      1.00      3910

confusion_matrix [[3192    1]
 [  11  706]]
accuray_score 0.9969309462915601
precission_score 0.9985855728429985
f1_score 0.9915730337078652
recall_score 0.9846582984658299
----------------------------------------------------------------------
prediction for x_test
classification_report               precision    recall  f1-score   support

           0       0.92      0.99      0.95       775
           1       0.94      0.65      0.77       203

    accuracy                           0.92       978
   macro avg       0.93      0.82      0.86       978
weighted avg       0.92      0.92      0.91       978

confusion_mat

In [89]:
import pickle 
pickle.dump(rf,open('random.pkl','wb'))