In [1]:
! pip install numpy



[notice] A new release of pip is available: 24.2 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

list=np.array([1,2,3,4])
print(list)

[1 2 3 4]


In [9]:
print(type(list))
print(list.shape)
print(list.reshape(4,1))

<class 'numpy.ndarray'>
(4,)
[[1]
 [2]
 [3]
 [4]]


In [10]:
list1=np.array([[1,2,3,4],[5,6,7,8]])
print(list1)
print(list1.shape)


[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [18]:
list2=np.arange(1,11).reshape(2,5)
print(list2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
## identity matrix

np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
print(list1.ndim)
print(list1.dtype)

2
int64


In [26]:
arry=np.array([1,2,3,4,5])
arry1=np.array([2,3,56,67,65])

print(f"addtion of two list is {arry+arry1}")
print(f"sub of two list is {arry-arry1}")
print(f"mult of two list is {arry*arry1}")
print(f"div of two list is {arry/arry1}")


addtion of two list is [ 3  5 59 71 70]
sub of two list is [ -1  -1 -53 -63 -60]
mult of two list is [  2   6 168 268 325]
div of two list is [0.5        0.66666667 0.05357143 0.05970149 0.07692308]


In [27]:
np.sqrt(list1)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712]])

In [28]:
muitarry=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(muitarry)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
print(muitarry[0][1])##both are same
print(muitarry[0,1])


print(muitarry[1:,1:])
print(muitarry[1:][0:])

2
2
[[5 6]
 [8 9]]
[[4 5 6]
 [7 8 9]]


In [35]:
print(list)

[1 2 3 4]


In [42]:
print(np.mean(list))
print(np.std(list))
print(np.median(list))
mean=np.mean(list)
std=np.std(list)
normlizied=(list-mean)/std
print(f'normalized is {normlizied}')
print(f'variance {np.var(list)}')


2.5
1.118033988749895
2.5
normalized is [-1.34164079 -0.4472136   0.4472136   1.34164079]
variance 1.25


In [43]:
list2[(list2>2) & (list2<7)]

array([3, 4, 5, 6])

In [44]:
print(list2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
d=np.full((2,3),6, dtype="float")
print(d)

[[6. 6. 6.]
 [6. 6. 6.]]


In [10]:
d=np.full((2,3),6, dtype="complex",)
print(d)

[[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [12]:
l=np.linspace(1,10,20)
print(l)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [16]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr.flatten())
print(arr)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [14]:
arr=arr[arr>2]

In [15]:
print(arr)

[3 4 5 6 7 8]


In [17]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [19]:
print(f"transpose of matrix \n {a.T}")

transpose of matrix 
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [ ]:
import numpy as np


arry=np.random.randint(1,21,size=(5,5)) #### here print random numbers 1,20 with array size 5,5

In [3]:
arry

array([[ 1,  6,  4,  4, 10],
       [ 3, 18,  6, 18,  3],
       [11, 19,  9,  9, 14],
       [17, 20,  4,  8,  9],
       [20, 10, 12, 11,  6]], dtype=int32)

In [4]:
arry[:,2:3]=1 ####here making 3rd coloumn of every row =1

In [5]:
arry

array([[ 1,  6,  1,  4, 10],
       [ 3, 18,  1, 18,  3],
       [11, 19,  1,  9, 14],
       [17, 20,  1,  8,  9],
       [20, 10,  1, 11,  6]], dtype=int32)

In [6]:
arr=np.random.randint(1,17,size=(4,4))

In [7]:
arr ###oringal array

array([[10,  5, 16,  5],
       [10,  2, 10, 15],
       [ 6, 11, 13, 12],
       [14,  5,  1, 11]], dtype=int32)

In [8]:
### here we are modifying arry 

#### make diagonal elements 0

np.fill_diagonal(arr,0)

In [9]:
arr #### modifyied array

array([[ 0,  5, 16,  5],
       [10,  0, 10, 15],
       [ 6, 11,  0, 12],
       [14,  5,  1,  0]], dtype=int32)

In [10]:
arry1=np.random.randint(1,37,size=(6,6))
arry1

array([[ 3, 20, 33, 32, 21, 19],
       [19, 12,  8, 32, 13, 18],
       [34, 33, 21, 33, 17,  3],
       [ 5,  7, 27,  3, 27,  2],
       [36, 21,  3, 33,  3, 31],
       [33, 33,  7, 23, 17,  3]], dtype=int32)

In [11]:
arry2=arry1[2:5,1:4] ####here we create sub arry from above arry

In [12]:
arry2 ###this sub array

array([[33, 21, 33],
       [ 7, 27,  3],
       [21,  3, 33]], dtype=int32)

In [14]:
arry=np.random.randint(1,25,size=(5,5))
arry

array([[24,  3,  7, 24, 13],
       [ 7, 15,  3,  1,  9],
       [20,  3,  6,  6, 10],
       [23, 22, 17, 13,  1],
       [19, 23,  4, 14,  1]], dtype=int32)

In [16]:
sub=np.concatenate((arry[0,:],arry[-1,:],arry[1:-1,0],arry[1:-1,1]))
sub

array([24,  3,  7, 24, 13, 19, 23,  4, 14,  1,  7, 20, 23, 15,  3, 22],
      dtype=int32)

In [17]:
arry1=np.random.randint(1,20,size=(3,4))
arry2=np.random.randint(1,20,size=(3,4))


In [18]:
arry1

array([[ 2,  2, 15, 12],
       [ 6,  8,  3, 13],
       [ 8,  3, 16, 14]], dtype=int32)

In [19]:
arry2

array([[17,  4, 13, 11],
       [12,  8,  7,  6],
       [ 2, 11, 17, 18]], dtype=int32)

In [30]:
print(f"addition of two arry is \n{arry1+arry2}")
print(f"sub of two arry is \n{arry1-arry2}")
print(f"div of two arry is \n{arry1/arry2}")
print(f"mult of two arry is \n{arry1*arry2}")
print(f"transpose of matrix arry1 is \n{arry1.T}")
print(f"transpose of matrix arry2 is \n{arry2.T}")
arry3=np.random.randint(1,20,size=(4,3))
print(arry3)
print(f"matrix multplication of matrix  is \n{arry1.dot(arry3)}")

addition of two arry is 
[[19  6 28 23]
 [18 16 10 19]
 [10 14 33 32]]
sub of two arry is 
[[-15  -2   2   1]
 [ -6   0  -4   7]
 [  6  -8  -1  -4]]
div of two arry is 
[[0.11764706 0.5        1.15384615 1.09090909]
 [0.5        1.         0.42857143 2.16666667]
 [4.         0.27272727 0.94117647 0.77777778]]
mult of two arry is 
[[ 34   8 195 132]
 [ 72  64  21  78]
 [ 16  33 272 252]]
transpose of matrix arry1 is 
[[ 2  6  8]
 [ 2  8  3]
 [15  3 16]
 [12 13 14]]
transpose of matrix arry2 is 
[[17 12  2]
 [ 4  8 11]
 [13  7 17]
 [11  6 18]]
[[17  5  1]
 [14 15 18]
 [10 17  6]
 [ 7  8  1]]
matrix multplication of matrix  is 
[[296 391 140]
 [335 305 181]
 [436 469 172]]


In [31]:
#### here we are doing row wise and column wise sum

arry1=np.random.randint(1,5,size=(2,2))

print(f"original matrix is {arry1}")

row=np.sum(arry1,axis=1)
column=np.sum(arry1,axis=0)

print(f"row sum is {row}")
print(f"column sum is {column}")

original matrix is [[4 4]
 [2 4]]
row sum is [8 6]
column sum is [6 8]


In [32]:
array = np.random.randint(1, 11, size=(3, 3))
row_array = np.random.randint(1, 11, size=(3,))
print("Original array:")
print(array)
print("1D array:")
print(row_array)

# Add the 1D array to each row of the 2D array using broadcasting
result = array + row_array
print("Resulting array:")
print(result)

Original array:
[[4 8 9]
 [9 4 5]
 [5 9 2]]
1D array:
[10  6  1]
Resulting array:
[[14 14 10]
 [19 10  6]
 [15 15  3]]


In [33]:
array = np.random.randint(1, 11, size=(4, 4))
column_array = np.random.randint(1, 11, size=(4,))
print("Original array:")
print(array)
print("1D array:")
print(column_array)

# Subtract the 1D array from each column of the 2D array using broadcasting
result = array - column_array[:, np.newaxis]
print("Resulting array:")
print(result)

Original array:
[[3 3 9 5]
 [7 6 5 6]
 [7 8 3 4]
 [8 1 9 4]]
1D array:
[4 3 2 4]
Resulting array:
[[-1 -1  5  1]
 [ 4  3  2  3]
 [ 5  6  1  2]
 [ 4 -3  5  0]]


In [36]:
arry=np.random.randint(1,5,size=(3,3))
print(f"original arry is \n {arry}")


det=np.linalg.det(arry)
inv=np.linalg.inv(arry)
ign=np.linalg.eigvals(arry)

print(f"determinte of matrix is {det}")
print(f"inverse of matrix is {inv}")
print(f"eigan of matrix is {ign}")

original arry is 
 [[2 1 1]
 [4 3 2]
 [3 3 1]]
determinte of matrix is -0.9999999999999996
inverse of matrix is [[ 3.00000000e+00 -2.00000000e+00  1.00000000e+00]
 [-2.00000000e+00  1.00000000e+00 -2.96059473e-16]
 [-3.00000000e+00  3.00000000e+00 -2.00000000e+00]]
eigan of matrix is [ 6.29257994  0.2783488  -0.57092874]


In [3]:
import numpy as np

arry=np.random.randint(1,20,size=(3,3))
print(arry)

arry[arry<10]=10
print(arry)

[[ 5 15  1]
 [ 1  2 10]
 [ 6 11 13]]
[[10 15 10]
 [10 10 10]
 [10 11 13]]


In [4]:
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


In [6]:
import numpy.ma as ma

arry=np.random.randint(1,20,size=(3,3))
maked=ma.masked_greater(arry,10)
print(f"original array is {arry}")
print(f"masked array is {maked}")

sum_masked=maked.sum()
print(f"sum masked array is {sum_masked}")

original array is [[ 1  6  7]
 [14  5  4]
 [ 5 16  3]]
masked array is [[1 6 7]
 [-- 5 4]
 [5 -- 3]]
sum masked array is 31
