#### KNN WE CAN SLOVE BOTH CLASSIFICATION AND REGRESSER

In [2]:
import pandas as pd
import numpy as np
from sklearn.datasets import make_classification

In [3]:
x,y=make_classification(n_samples=1000,n_features=2,n_classes=2,n_redundant=0)

In [4]:
x

array([[ 0.75307062,  1.0147721 ],
       [-0.67698358, -1.35902456],
       [ 2.47606519, -0.24204352],
       ...,
       [-0.19290681, -1.8512779 ],
       [-0.10696399, -1.57018265],
       [-2.23715449,  0.31846513]], shape=(1000, 2))

In [5]:
y

array([1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

In [11]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=4,algorithm='auto')

In [12]:
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=4)

In [13]:
y_pred=knn.predict(x_test)

In [14]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))


0.975
              precision    recall  f1-score   support

           0       0.97      0.98      0.97        95
           1       0.98      0.97      0.98       105

    accuracy                           0.97       200
   macro avg       0.97      0.98      0.97       200
weighted avg       0.98      0.97      0.98       200

[[ 93   2]
 [  3 102]]


In [30]:
from sklearn.model_selection import GridSearchCV
pramas={
    "n_neighbors":[1,2,3,4,5,6,7,8],
    "algorithm":['kd_tree', 'auto', 'ball_tree', 'brute'],
    'metric':['eucliden','manhattan']
    
}

In [31]:
pramas

{'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8],
 'algorithm': ['kd_tree', 'auto', 'ball_tree', 'brute'],
 'metric': ['eucliden', 'manhattan']}

In [32]:
grid=GridSearchCV(estimator=knn,param_grid=pramas,cv=5,scoring='accuracy')

In [33]:
grid.fit(x_train,y_train)

c:\Users\dell\Documents\code\myenv\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
160 fits failed out of a total of 320.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
160 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\dell\Documents\code\myenv\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\dell\Documents\code\myenv\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "c:\Users\dell\Documents\code\myenv\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=4),
             param_grid={'algorithm': ['kd_tree', 'auto', 'ball_tree', 'brute'],
                         'metric': ['eucliden', 'manhattan'],
                         'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8]},
             scoring='accuracy')

In [34]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.975
              precision    recall  f1-score   support

           0       0.97      0.98      0.97        95
           1       0.98      0.97      0.98       105

    accuracy                           0.97       200
   macro avg       0.97      0.98      0.97       200
weighted avg       0.98      0.97      0.98       200

[[ 93   2]
 [  3 102]]


In [35]:
grid.best_params_


{'algorithm': 'kd_tree', 'metric': 'manhattan', 'n_neighbors': 2}